---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Check nginx version
  ansible.builtin.command: nginx -v
  register: nginx_version
  changed_when: false

#- name: Force failure for CI test
#  ansible.builtin.fail:
#    msg: "Intentional failure to test CI pipeline"
